### ISSUE TITLE
DB Schema 

### ISSUE THREAD

**Issue by sandip-narwade** [ikismail/ShoppingCart#21]
Hello Sir, I want try ur project for that I need .sql file can u provide it

**Comment by ikismail** [comment]
Hello @sandipJava  yu dnt need .sql file to import if you run the application #Hibernate automatically create your tables and column in your configured database schema just try it. If you face any problem ping me. 
Thanks

**Comment by ikismail** [comment]
closing this issue right now,.

**Comment by sandip-narwade** [comment]
@ikismail  thank You sir, I will try... If any prob I will connect u

**Comment by sandip-narwade** [comment]
it needs H2 DB. How I can used mysql db

**Comment by ikismail** [comment]
Just add mysql dependency to the pom.xml and in the applicationContext.xml modify the database properties [here is the link](https://github.com/ikismail/ShoppingCart/blob/master/src/main/webapp/WEB-INF/applicationContext.xml ). Change the dialect, driverClass and database properties according to your db.

**Comment by sandip-narwade** [comment]
Ok ... I will do, is it will create tables in mySql

**Comment by fatimazahrachaker** [comment]
hiiiii i have problem in Database did i shoud created ?!!!!
 i use mySql

**Comment by ikismail** [comment]
what problem are you facing ?. You can use mySQL. you have to configure you database properties correctly. Check it twice.

**Comment by fatimazahrachaker** [comment]
​
 EasyShope.rar
<https://drive.google.com/file/d/1roilkNhB9PI_iUQ1TrljtbJxnfZy0-en/view?usp=drive_web>
​

Le mer. 4 juil. 2018 à 15:11, Mohammed Ismail <notifications@github.com> a
écrit :
