### ISSUE TITLE
Need Db scripts

### ISSUE THREAD

**Issue by puneetgupta12** [ikismail/ShoppingCart#22]
I'd like to ask you for the Db scripts for the solution you posted here.

**Comment by mazhar266** [comment]
Have a look at the models under `src/main/java/com/model` folder. @puneetgupta12

**Comment by ikismail** [comment]
@puneetgupta12 you don't need any scripts for DB, Hibernate will automatically create the tables and columns based on the model as @mazhar266 told. thanks @mazhar266 closing this.
