### ISSUE TITLE
db connectivity problem

### ISSUE THREAD

**Issue by chirjot** [ikismail/ShoppingCart#24]
org.hibernate.exception.GenericJDBCException: Could not open connection

my credentials in the xml file are correct.

**Comment by ikismail** [comment]
Hi @chirjot can you share me the full error message in console?

**Comment by ahmadsolehin** [comment]
me too

**Comment by ikismail** [comment]
Kindly check once driverClassName and username and password.If u get again write a simple core java program to establish jDBC connection by using what ever parameters u have been used for hibernate and check.
