### ISSUE TITLE
Error : "Could not get database metadata"

### ISSUE THREAD

**Issue by PrashantBahuguna** [ikismail/ShoppingCart#26]
When the application is run on the server this exception is raised in the console. The webpage gets live but when new user is signed up the application crashes with the error : "Could not open connection".
![screenshot 34](https://user-images.githubusercontent.com/39057935/39739030-5af23666-52ac-11e8-96d7-7b200a89816a.png)

**Comment by ikismail** [comment]
@PrashantB248  Please verify your Database credentials, You have configured wrong username or password of your h2Database to the application.

**Comment by PrashantBahuguna** [comment]
![screenshot 35](https://user-images.githubusercontent.com/39057935/39739694-e534f810-52af-11e8-98d2-b36a79bbb62d.png)
![screenshot 36](https://user-images.githubusercontent.com/39057935/39739698-e8dc556c-52af-11e8-8e44-d757384aba9b.png)
I have checked, its "prashant" everywhere.

**Comment by ikismail** [comment]
@PrashantB248 the problem is your H2 settings. Change your H2 Database Settings to **Generic H2 (Server)**. so that the JDBC URL will change according to your properties.

![image](https://user-images.githubusercontent.com/17190913/39740058-8a9e1128-52b1-11e8-9b05-bc25dd4baa2e.png)

**Comment by PrashantB248** [comment]
![screenshot 37](https://user-images.githubusercontent.com/39057935/39740320-ba667a34-52b2-11e8-80c9-a13fcc934ddf.png)
I did it but now the application won't run..
"Connection is broken" error

**Comment by PrashantBahuguna** [comment]
![screenshot 38](https://user-images.githubusercontent.com/39057935/39740505-8782ab32-52b3-11e8-9a06-bb9261bc5e4f.png)
![screenshot 39](https://user-images.githubusercontent.com/39057935/39740508-89e0aaaa-52b3-11e8-9af2-be45295457ff.png)
The same issue is there..

**Comment by ikismail** [comment]
Your configuration is wrong verify it clearly.

**Comment by PrashantBahuguna** [comment]
Unable to find the problem..!

**Comment by ikismail** [comment]
Send the snapshot of current application-config.xml  and h2 settings

**Comment by PrashantBahuguna** [comment]
![screenshot 41](https://user-images.githubusercontent.com/39057935/39742701-1b7a60e8-52bc-11e8-80b1-bf25be2667d5.png)
![screenshot 42](https://user-images.githubusercontent.com/39057935/39742707-203a276c-52bc-11e8-81b4-201c8d1e017d.png)
Is there any issue in the DB url ?

**Comment by ikismail** [comment]
your application-context.xml database configuration should be like this.

```
<!-- database properties DataSouorce -->
   <bean id="dataSource"
       class="org.springframework.jdbc.datasource.DriverManagerDataSource">
     <property name="driverClassName" value="org.h2.Driver" />
     <property name="url" value="jdbc:h2:tcp://localhost/~/test" />
     <property name="username" value="prashant" />
     <property name="password" value="prashant" />
   </bean>
```

your h2 database settings should be like this.

![image](https://user-images.githubusercontent.com/17190913/39742901-d067f902-52bc-11e8-80e7-78aebd0e36e8.png)

now stop the server clean the server directory and start it.

**Comment by PrashantBahuguna** [comment]
![screenshot 43](https://user-images.githubusercontent.com/39057935/39743828-dffb6cb6-52bf-11e8-856e-3b0697a5b743.png)
Made the changes.
This issue has arised.

**Comment by ikismail** [comment]
reinstall your server

[Fix Eclipse Tomcat not starting in 45 seconds](https://sansatechnology.wordpress.com/2011/09/26/how-to-fix-eclipse-tomcat-not-starting-in-45-seconds/)

**Comment by PrashantBahuguna** [comment]
Solved..!!
Live and running.
Thank You so much for your help.!

**Comment by ChillBoss** [comment]
Bro..where is the database file?? like,i want the tables

**Comment by ikismail** [comment]
@ChillBoss I hope  this will work [How to open and export data from h2 bb](http://cassacloud.com/how-to-open-and-export-data-from-h2-java-database/).
