### ISSUE TITLE
Admin Login

### ISSUE THREAD

**Issue by PrashantBahuguna** [ikismail/ShoppingCart#27]
How to login as an Admin ?
What are the login details ?
Will the product details be added via Admin page because currently it is empty.

**Comment by ikismail** [comment]
1. Register new User
2. In database you can see the registered user details in user table.
3. In Authorities table you can see the registered  user role as ROLE_USER
Modify to ROLE_ADMIN and login again you can get the admin features.

**Comment by PrashantBahuguna** [comment]
Products are not getting added to cart.
Have you implemented this functionality ?

**Comment by ikismail** [comment]
yes

**Comment by PrashantBahuguna** [comment]
but it's not working, there is no event on clicking add to cart icon next to the product and the cart remains empty.

**Comment by PrashantBahuguna** [comment]
Also the functionality of displaying all users in DB to admin is also not there along with many more.

**Comment by ikismail** [comment]
sorry for the delay @PrashantB248 kindly check the console for the errors and let me know will solve the issue. And Displaying All users is not Implemented. thanks

**Comment by Haneesh001** [comment]
Products are not getting added to cart.
Have you implemented this functionality ?

**Comment by Haneesh001** [comment]
but it's not working, there is no event on clicking add to cart icon next to the product and the cart remains empty.

**Comment by Haneesh001** [comment]
Also the functionality of displaying all users in DB to admin is also not there along with many more

**Comment by raju-120** [comment]
the cart option did not work out..
