### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by h4cker39** [ikismail/ShoppingCart#34]
Hi @ikismail I am an Application Security professional and also part-time developer on my projects. My current used framework is Spring and technology is Java. I forked a controller Class in your project due to possible  sql injection vulnerability by number.
If you need any further help I would like to contribute more. And there are also other issues regarding the e-commerce. Like possibly the other controllers.

**Comment by ikismail** [comment]
Hi @h4cker39, 👏 Contributors are always welcome
