### ISSUE TITLE
DatabaseUsage

### ISSUE THREAD

**Issue by Joyrocky** [ikismail/ShoppingCart#36]
首先在这里感谢一下项目设计者，但是在连接数据库时出现了一些问题，请问在IDEA中新建数据库后怎么将数据导入H2数据库运行。且仅建立数据库后运行tomacat后出现下列错误，希望作者能够提一些建议
[Exception.pdf](https://github.com/ikismail/ShoppingCart/files/2778210/Exception.pdf)

**Comment by ikismail** [comment]
感谢您使用此repo，问题是您的servlet无法识别bean类路径。 检查base-href以正确扫描控制器，bean和服务。
检查webapp文件夹中dispatcher-servlet.xml文件中的第15行。

Check the file here. [File Path](https://github.com/ikismail/ShoppingCart/blob/master/src/main/webapp/WEB-INF/dispatcher-servlet.xml)

**Comment by Joyrocky** [comment]
> 感谢您使用此repo，问题是您的servlet无法识别bean类路径。 检查base-href以正确扫描控制器，bean和服务。
> 检查webapp文件夹中dispatcher-servlet.xml文件中的第15行。
> 
> Check the file here. [File Path](https://github.com/ikismail/ShoppingCart/blob/master/src/main/webapp/WEB-INF/dispatcher-servlet.xml)

原来的地方是com.报这个错误，我改成了com.controller，还是这个错误。那个form表单中无法识别commandName-“order”，
![default](https://user-images.githubusercontent.com/23481533/51786548-b82dbd00-21a0-11e9-8087-e7a13e81028d.PNG)
角色认证也无法识别“ifAnyGranted”属性
![2](https://user-images.githubusercontent.com/23481533/51786553-bfed6180-21a0-11e9-82b7-1748028edae4.PNG)
请问该怎么办  :fearful:

**Comment by ikismail** [comment]
您必须提供扫描所有控制器，模型和服务的基本路径
